# Generated by Django 5.0.6 on 2024-06-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_remove_carousel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
